### ISSUE TITLE
Error deploying Express app with 'fast-two-sms' package on Vercel due to 'is-ci' module not found

### ISSUE THREAD

**Issue by bidhannath** [watson/is-ci#26] opened 2023-07-08 08:53 UTC
I am currently attempting to deploy an Express app on Vercel as a Serverless function. To handle SMS functionality, I have integrated the 'fast-two-sms' package into my project. However, during the deployment process on Vercel, I encountered an error stating that the 'is-ci' module was not found. I suspect that this issue may be related to the case-sensitive file system of Vercel, as mentioned in their documentation: https://vercel.com/guides/how-do-i-resolve-a-module-not-found-error.

**Comment by sibiraj-s** [comment] 2023-07-10 07:23
Thanks for opening the issue. But I don't understand how is this a problem with `is-ci`. A problem reported on a package doesn't mean the problem is with the package.

Closing this issue as there is no enough context/information to debug this. Feel free to reopen this with more info or a way to reproduce. Happy to help.

**Closed as completed by sibiraj-s** 2023-07-10 07:23 UTC

**Comment by bidhannath** [comment] 2023-07-14 15:36
Hi @sibiraj-s, 
Apologies! I could not come up with enough information. I will raise this with Vercel and check once, as I am still unable to deploy my express app.
Thanks,
Bidhan

**Comment by sibiraj-s** [comment] 2023-07-15 03:18
Sure. Thanks @bidhannath . Feel free to reopen if needed.
